import type {Metadata} from "next";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";
import {Toaster} from '@/lib/components/ui/sonner';
import {cn} from "@/lib/utils";
import {Inter} from 'next/font/google';

const inter = Inter({subsets: ['latin'], variable: '--font-sans'});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={cn('min-h-screen bg-background font-sans antialiased', inter.variable)}>
        <ClerkProvider>{children}</ClerkProvider>
        <Toaster/>
        </body>
        </html>
    );
}
